spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/flightBookingDB_dev

logging:
  level:
    com.flightapp: TRACE
    org.springframework.web: DEBUG
  file:
    name: logs/flight-booking-dev.log